Add Yubico OTP
greeveu/Bungeecord-2FA pull request #9
Opened 2023-01-16 18:48 UTC by Alex1607

2023-01-16 18:54 UTC, Achsion commented
does it work with more than one yubikey?

2023-01-17 00:13 UTC, Alex1607 commented
> does it work with more than one yubikey?

It does now ^^

2023-01-17 23:39 UTC, Achsion requested changes

2023-01-17 23:39 UTC, Achsion commented on src/main/java/eu/greev/twofa/api/impl/APIImpl.java
> +    public APIImpl(TwoFaDao dao) {
use `@RequiredArgsContructor` instead

2023-01-17 23:39 UTC, Achsion commented on src/main/java/eu/greev/twofa/commands/TwoFACommand.java
> +                if (args.length >= 2) {
Missing help message for `args.length == 1`

2023-01-17 23:39 UTC, Achsion commented on src/main/java/eu/greev/twofa/entities/User.java
> +    private static final Map<UUID, User> SPIELER_MAP = new HashMap<>();
```suggestion
    private static final Map<UUID, User> USER_MAP = new HashMap<>();
```
is now a User ^^

2023-01-17 23:39 UTC, Achsion commented on src/main/java/eu/greev/twofa/listeners/ChatListener.java
> +    public ChatListener(TwoFaService service, Language language) {
use `@RequiredArgsContructor` instead

2023-01-17 23:39 UTC, Achsion commented on src/main/java/eu/greev/twofa/listeners/ServerSwitchListener.java
> +    public ServerSwitchListener(TwoFaService service, Language language) {
use `@RequiredArgsContructor` instead

2023-01-17 23:39 UTC, Achsion commented on src/main/java/eu/greev/twofa/service/TwoFaService.java
> +    public TwoFaService(TwoFactorAuth main, TwoFaDao database, YubicoClient yubicoClient, TwoFactorAuthUtil twoFactorAuthUtil, Language language) {
use `@RequiredArgsContructor` instead

2023-01-17 23:39 UTC, Achsion commented on src/main/java/eu/greev/twofa/utils/ConfigUtils.java
> +    public ConfigUtils(Plugin plugin) {
use `@RequiredArgsContructor` instead

2023-01-17 23:39 UTC, Achsion commented on src/main/java/eu/greev/twofa/utils/Language.java
> +        yubicoCodeInvalid = configuration.getString("messages.invalidcode").replace("&", "§");
```suggestion
```
looks like this isn't needed anymore

2023-01-18 21:45 UTC, merged